### ISSUE TITLE
App crashes when changing organization

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/gateway-edit#124]
Wrote this up while testing #72

To reproduce:

Log in
Choose an org and language
When the project opens, open the drawer
Choose a different org and click Save and Continue
Note the app reports an "An unexpected error has occurred."

**Comment by PhotoNomad0** [comment]
@cckozie This looks like new breakage handling missing repos.  Likely due to my refactor to show loading status.

I can reproduce.  @birchamp Recommend a high priority on this.

**Comment by PhotoNomad0** [comment]
@cckozie This should be fixed in build v0.2.0 build dbfbebc
@elsylambert

**Comment by elsylambert** [comment]
v0.9.0 build ab13659

@PhotoNomad0 still seeing this issue. I logged in and the changed the organization and got the error.
![Screen Shot 2021-03-30 at 12.14.46 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/11922b34-aa14-40f3-bdd2-c458dc02f01d)

**Comment by PhotoNomad0** [comment]
@elsylambert Can you attach a screenshot of the console.log so I can see the errors?

**Comment by elsylambert** [comment]
v0.9.0 build a6e30e1
@PhotoNomad0 
![Screen Shot 2021-03-31 at 11.38.42 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/f1aacc0a-0b82-468f-8b6a-08afa5743125)

**Comment by PhotoNomad0** [comment]
@elsylambert Thanks will try testing with unfoldingWord organization.

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie Fix for crash in unfoldingWord org is in v0.9.0 build da4bfd6

**Comment by elsylambert** [comment]
App is not crashing when changing organization in v0.9.0 build 4ec92f2.

**Comment by cckozie** [comment]
Not seeing the problem in v0.9.0 build f601ed4

**Comment by elsylambert** [comment]
Tested in gE_App crash Test.
